package es.studium.hibernate;
// Generated 10 nov 2021 10:32:12 by Hibernate Tools 5.5.7.Final

/**
 * Dogs generated by hbm2java
 */
public class Dogs implements java.io.Serializable {

	private Integer id;
	private String raza;
	private String tamano;
	private int edad;
	private String color;

	public Dogs() {
	}

	public Dogs(String raza, String tamano, int edad, String color) {
		this.raza = raza;
		this.tamano = tamano;
		this.edad = edad;
		this.color = color;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public String getTamano() {
		return this.tamano;
	}

	public void setTamano(String tamano) {
		this.tamano = tamano;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
