package es.studium.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 15 nov 2021 10:45:43 by Hibernate Tools 5.5.7.Final

/**
 * Dogs generated by hbm2java
 */
@Entity
@Table(name="dogs", schema="ad")

public class Dogs implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column (name = "id")
	private Integer id;
	@Column (name = "raza")
	private String raza;
	@Column (name = "tamano")
	private String tamano;
	@Column (name = "edad")
	private int edad;
	@Column (name = "color")
	private String color;

	public Dogs() {
	}

	public Dogs(String raza, String tamano, int edad, String color) {
		this.raza = raza;
		this.tamano = tamano;
		this.edad = edad;
		this.color = color;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public String getTamano() {
		return this.tamano;
	}

	public void setTamano(String tamano) {
		this.tamano = tamano;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
