package es.studium.hibernate;
// Generated 15 nov 2021 9:06:49 by Hibernate Tools 5.5.7.Final

/**
 * Movies generated by hbm2java
 */
public class Movies implements java.io.Serializable {

	private Integer idPelicula;
	private Personas personas;
	private String titulo;
	private int ano;
	private int duracion;

	public Movies() {
	}

	public Movies(Personas personas, String titulo, int ano, int duracion) {
		this.personas = personas;
		this.titulo = titulo;
		this.ano = ano;
		this.duracion = duracion;
	}

	public Integer getIdPelicula() {
		return this.idPelicula;
	}

	public void setIdPelicula(Integer idPelicula) {
		this.idPelicula = idPelicula;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getAno() {
		return this.ano;
	}

	public void setAno(int ano) {
		this.ano = ano;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

}
