package es.studium.hibernate;
// Generated 15 nov 2021 9:06:49 by Hibernate Tools 5.5.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

	private Integer idPersona;
	private String nombre;
	private Date fechaNacimiento;
	private Set movieses = new HashSet(0);

	public Personas() {
	}

	public Personas(String nombre, Date fechaNacimiento) {
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Personas(String nombre, Date fechaNacimiento, Set movieses) {
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.movieses = movieses;
	}

	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Set getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set movieses) {
		this.movieses = movieses;
	}

}
